CC=gcc
CFLAGS= -Wall -Wextra -Werror
SOURCES=s21_grep.c s21_grep.h

s21_grep: 
	$(CC) $(CFLAGS) $(SOURCES) -o s21_grep

clean:
	rm s21_grep

rebuild:
	rm s21_grep
	$(CC) $(CFLAGS) $(SOURCES) -o s21_grep
test: 
	sh test.sh > logg.txt